### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by wentuq** [drotiro/libebook#1]
It will be great if you will add dependencies, in Ubuntu for sure i needed:
- libzip-dev
- not sure about libxml2

And I cannot compile it until I created inside main folder subfolders:
- bin
- lib

**Comment by drotiro** [comment]
Hi!
These dependencies are listed in src/Makefile, using pkg-config.
If one of them is missing, you should get a message like this:

> Package libzip was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libzip.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libzip' found

Added directory creation.

Thank you for your comments,
regards.

Domenico.
